language: node_js

node_js:
  - "node"

env:
  - ENV=travis

services:
  - postgresql

cache:
  directories:
    - node_modules

before_script:
  - psql -c 'create database politico_test;' -U postgres

after_script:
  - npm run coveralls
