
const users = [
  {
    firstname: 'Kenneth',
    lastname: 'Onah',
    email: 'kenzdozz@gmail.com',
    phonenumber: '07032328612',
    password: 'chidozie',
    isadmin: true,
    gender: 'Male',
    passporturl: 'https://cdn5.vectorstock.com/i/thumb-large/73/14/young-man-wearing-sleeveless-top-faceless-avata-vector-15127314.jpg',
  },
  {
    firstname: 'John',
    lastname: 'Doe',
    email: 'john@doe.com',
    phonenumber: '908837612',
    password: 'johndoe',
    gender: 'Male',
    passporturl: 'https://previews.123rf.com/images/rikkyal/rikkyal1712/rikkyal171200013/90908350-bearded-man-s-face-hipster-character-fashion-silhouette-avata.jpg',
  },
  {
    firstname: 'Jane',
    lastname: 'Jones',
    email: 'jane@jones.com',
    phonenumber: '44032328698',
    password: 'doejane',
    gender: 'Female',
    passporturl: 'https://cdn5.vectorstock.com/i/thumb-large/73/14/young-man-wearing-sleeveless-top-faceless-avata-vector-15127314.jpg',
  },
  {
    firstname: 'Victor',
    lastname: 'Davis',
    email: 'veeq@davis.com',
    phonenumber: '07901328698',
    password: 'veeqdave',
    gender: 'Male',
    passporturl: 'https://cdn5.vectorstock.com/i/thumb-large/73/14/young-man-wearing-sleeveless-top-faceless-avata-vector-15127314.jpg',
  },
  {
    firstname: 'Charles',
    lastname: 'Benson',
    email: 'benson@gmail.com',
    phonenumber: '070892786132',
    password: 'bencharly',
    gender: 'Male',
    passporturl: 'https://cdn5.vectorstock.com/i/thumb-large/73/14/young-man-wearing-sleeveless-top-faceless-avata-vector-15127314.jpg',
  },
  {
    firstname: 'Amaka',
    lastname: 'Dissap',
    email: 'damaka@gmail.com',
    phonenumber: '090092878612',
    password: 'dissapamaka',
    gender: 'Female',
    passporturl: 'https://previews.123rf.com/images/rikkyal/rikkyal1712/rikkyal171200013/90908350-bearded-man-s-face-hipster-character-fashion-silhouette-avata.jpg',
  },
  {
    firstname: 'Emmanuel',
    lastname: 'Maka',
    email: 'emma@yahoo.com',
    phonenumber: '070932328698',
    password: 'makanuel',
    gender: 'Female',
    passporturl: 'https://cdn5.vectorstock.com/i/thumb-large/73/14/young-man-wearing-sleeveless-top-faceless-avata-vector-15127314.jpg',
  },
];

export default users;
